### ISSUE TITLE
LIBRSVG Support

### ISSUE THREAD

**Issue by DannyAziz** [serverlesspub/imagemagick-aws-lambda-2#2]
I tried following the makefile from https://github.com/serverlesspub/rsvg-convert-aws-lambda-binary and added --with-rsvg=yes to the imagemagick `./configure` but I still can't get this to work

Am I missing something?

**Comment by albertgcsula** [comment]
@DannyAziz you have to make sure either <a href="http://developer.gnome.org/rsvg/" target="_blank">RSVG</a> or <a href="http://www.inkscape.org/" target="_blank">inkscape</a> are available in the execution path. From the docs <a href="https://imagemagick.org/script/formats.php" target="_blank">here</a>: "ImageMagick utilizes inkscape if its in your execution path otherwise RSVG. If neither are available, ImageMagick reverts to its internal SVG renderer. The default resolution is 96 DPI. Use -size command line option to specify the maximum width and height. If you want to render a very large SVG and you trust the source, enable this option: -define svg:xml-parse-huge=true."
